### ISSUE TITLE
error installing application

### ISSUE THREAD

**Issue by githubevodigital** [velezandresf/MoviesIncBaufest#2]
i'm getting this error:

npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 980 file(s) to forward-jetify. Using 12 workers...
:ReactNative:Unexpected empty result of running '[node, C:\testEVO\Andrés\MoviesIncBaufest\node_modules\@react-native-community\cli\build\bin.js, config]' command.
:ReactNative:Running '[node, C:\testEVO\Andrés\MoviesIncBaufest\node_modules\@react-native-community\cli\build\bin.js, config]' command failed.
> Evaluating settingsITIALIZING [23ms]
FAILURE: Build failed with an exception.

* Where:
Script 'C:\testEVO\Andr�s\MoviesIncBaufest\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 205

* What went wrong:
A problem occurred evaluating script.
> node:internal/modules/cjs/loader:930  throw err;  ^Error: Cannot find module 'C:\testEVO\AndrÃ©s\MoviesIncBaufest\node_modules\@react-native-community\cli\build\bin.js'    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)    at Function.Module._load (node:internal/modules/cjs/loader:772:27)    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)    at node:internal/main/run_main_module:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
:ReactNative:Unexpected empty result of running '[node, C:\testEVO\Andrés\MoviesIncBaufest\node_modules\@react-native-community\cli\build\bin.js, config]' command.
:ReactNative:Running '[node, C:\testEVO\Andrés\MoviesIncBaufest\node_modules\@react-native-community\cli\build\bin.js, config]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\testEVO\Andr�s\MoviesIncBaufest\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 205

* What went wrong:
A problem occurred evaluating script.
> node:internal/modules/cjs/loader:930  throw err;  ^Error: Cannot find module 'C:\testEVO\AndrÃ©s\MoviesIncBaufest\node_modules\@react-native-community\cli\build\bin.js'    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)    at Function.Module._load (node:internal/modules/cjs/loader:772:27)    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)    at node:internal/main/run_main_module:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

    at makeError (c:\testEVO\Andrés\MoviesIncBaufest\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at c:\testEVO\Andrés\MoviesIncBaufest\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (c:\testEVO\Andrés\MoviesIncBaufest\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (c:\testEVO\Andrés\MoviesIncBaufest\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.

**Comment by githubevodigital** [comment]
El error era de entorno local

**Comment by velezandresf** [comment]
Hola, 

Ya pudiste probar la aplicación en Android? o el error persiste? 

Saludos
